const ARTIST_DETAILS = [
  { 
    name: "Jodie Hartland", 
    title: "Artwork Title",
    tagline: "A short description of the artwork to introduce the visitor.",
    description: "A much longer piece of writing, spanning multiple lines, with markdown",
    image: "../img/jodie/artwork.png",
    contact: "email",
  },
  { 
    name:"James Hancock",
    title: "DISCONTENT",
    tagline: "A short description of the artwork to introduce the visitor.",
    description: "A much longer piece of writing, spanning multiple lines, with markdown",
    image: "../img/james/fingerprint.png",
    contact: "email", 
  },
  { 
    name:"Vincent Keep",
    title: "Artwork Title",
    tagline: "A short description of the artwork to introduce the visitor.",
    description: "A much longer piece of writing, spanning multiple lines, with markdown",
    image: "../img/james/labyrinth.png",
    contact: "email", 
  },
  { 
    name:"Chonlachat Srisompetch",
    title: "Artwork Title",
    tagline: "A short description of the artwork to introduce the visitor.",
    description: "A much longer piece of writing, spanning multiple lines, with markdown",
    image: "../img/jodie/artwork.png",
    contact: "email", 
  },
  { 
    name:"Tim McCarthy",
    title: "Artwork Title",
    tagline: "A short description of the artwork to introduce the visitor.",
    description: "A much longer piece of writing, spanning multiple lines, with markdown",
    image: "../img/jodie/artwork.png",
    contact: "email", 
  },
  { 
    name:"Ena Koitabashi",
    title: "Artwork Title",
    tagline: "A short description of the artwork to introduce the visitor.",
    description: "A much longer piece of writing, spanning multiple lines, with markdown",
    image: "../img/jodie/artwork.png",
    contact: "email", 
  },
  { 
    name:"Patrick Robinson",
    title: "Artwork Title",
    tagline: "A short description of the artwork to introduce the visitor.",
    description: "A much longer piece of writing, spanning multiple lines, with markdown",
    image: "../img/jodie/artwork.png",
    contact: "email", 
  },
  { 
    name:"Jiaxian Liang",
    title: "Artwork Title",
    tagline: "A short description of the artwork to introduce the visitor.",
    description: "A much longer piece of writing, spanning multiple lines, with markdown",
    image: "../img/jodie/artwork.png",
    contact: "email", 
  },
  { 
    name:"Jack Myers",
    title: "Artwork Title",
    tagline: "A short description of the artwork to introduce the visitor.",
    description: "A much longer piece of writing, spanning multiple lines, with markdown",
    image: "../img/jodie/artwork.png",
    contact: "email", 
  },
  { 
    name:"Omar Hamouda",
    title: "Artwork Title",
    tagline: "A short description of the artwork to introduce the visitor.",
    description: "A much longer piece of writing, spanning multiple lines, with markdown",
    image: "../img/jodie/artwork.png",
    contact: "email", 
  },
  { 
    name:"Molly Stanners Putland",
    title: "Artwork Title",
    tagline: "A short description of the artwork to introduce the visitor.",
    description: "A much longer piece of writing, spanning multiple lines, with markdown",
    image: "../img/jodie/artwork.png",
    contact: "email", 
  },
  { 
    name:"Puppyuck",
    title: "Artwork Title",
    tagline: "A short description of the artwork to introduce the visitor.",
    description: "A much longer piece of writing, spanning multiple lines, with markdown",
    image: "../img/puppyuck/artwork.png",
    contact: "email", 
  },
  { 
    name:"Lemayr",
    title: "Artwork Title",
    tagline: "A short description of the artwork to introduce the visitor.",
    description: "A much longer piece of writing, spanning multiple lines, with markdown",
    image: "../img/jodie/artwork.png",
    contact: "email", 
  }
]

/*
    this.artistNames = [ 
      "Jodie Hartland",
      "James Hancock",
      "Fraser Owens",
      "Chonlachat Srisompetch",
      "Tim McCarthy",
      "Ena Koitabashi",
      "Patrick Robinson",
      "Jiaxian Liang",
      "Jack Myers",
      "Omar Hamouda",
      "Molly Stanners Putland",
      "Ches Wintie",
      "Eille Robinson" 
    ];
*/

export default ARTIST_DETAILS;